#!/bin/bash
set -e

if [ -n "$ORACLE_APP_USER" ] && [ -n "$ORACLE_APP_USER_PASSWORD" ]; then
  echo "Creating application user: $ORACLE_APP_USER"

  sqlplus -s / as sysdba <<EOF
ALTER SESSION SET CONTAINER = ${ORACLE_PDB:-FREEPDB1};
CREATE USER ${ORACLE_APP_USER} IDENTIFIED BY ${ORACLE_APP_USER_PASSWORD};
GRANT CONNECT, RESOURCE TO ${ORACLE_APP_USER};
GRANT UNLIMITED TABLESPACE TO ${ORACLE_APP_USER};
EXIT;
EOF
fi