juggling.project=/data/project
juggling.sample=true
juggling.runtime=resin
juggling.env=ut

target=/data
juggling.dest=${target}/war
juggling.dest.static=${target}/public
juggling.work=${target}/repository
juggling.war=${target}/imart.war
juggling.static=${target}/imart.zip

juggling.repository.base=http://repository.intra-mart.jp/base
juggling.repository.app=http://repository.intra-mart.jp/app